# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "264f3f23a6c75159cb21ee8fdda1914c"
name = "product-price-drop"
handle = "product-price-drop"
application_url = "https://fight-florida-newfoundland-ana.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "dukeshill-custom-fields.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://fight-florida-newfoundland-ana.trycloudflare.com/auth/callback",
  "https://fight-florida-newfoundland-ana.trycloudflare.com/auth/shopify/callback",
  "https://fight-florida-newfoundland-ana.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
